baseurl: '/'
permalink: pretty
title: 'Thomas Guignard Consulting'

logo:
  mobile: "images/logo/TGCG-logotype.png"
  mobile_height: "32px"
  mobile_width: "55px"
  desktop: "images/logo/TGCG-logotype.png"
  desktop_height: "100px"
  desktop_width: "173px"

home: 
  limit_services: 6 

collections:
  projects:
    output: true
    sort_by: weight
  team:
      output: false

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
